### ISSUE TITLE
[Bug] Error loading documents to Pinecone

### ISSUE THREAD

**Issue by ricardopinto** [pinecone-io/pinecone-python-client#166]
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Throws an error when loading document vectors into Pinecone.

### Expected Behavior

I was expecting document vectors to be added to the index.

### Steps To Reproduce

1. Clone this repo https://github.com/ricardopinto/pinecone-test
2. Update the code in `qa_docs.py` and add your apy key, region, and index name (5120 dimensions)
3. Follow the instructions in the readme to download the model and start the app

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1076, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.10/http/client.py", line 998, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/qa_docs.py", line 27, in <module>
    docsearch = Pinecone.from_documents(texts, embeddings, index_name=index_name)
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/base.py", line 218, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/pinecone.py", line 246, in from_texts
    index.upsert(vectors=list(to_upsert), namespace=namespace)
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/utils/error_handling.py", line 17, in inner_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pinecone/index.py", line 147, in upsert
    return self._upsert_batch(vectors, namespace, _check_type, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pinecone/index.py", line 231, in _upsert_batch
    return self._vector_api.upsert(
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/api/vector_operations_api.py", line 956, in __upsert
    return self.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/api_client.py", line 459, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/rest.py", line 271, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.10/dist-packages/pinecone/core/client/rest.py", line 157, in request
    r = self.pool_manager.request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='test-7ae06e9.svc.asia-northeast1-gcp.pinecone.io', port=443): Max retries exceeded with url: /vectors/upsert (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2396)')))
```

### Environment

```markdown
- OS: Ubuntu 22.04 host, docker image from ubuntu 22.04
- Python: 3.10.6
- pinecone: 2.2.1
```

### Additional Context

reproducible code: https://github.com/ricardopinto/pinecone-test

**Comment by jhamon** [comment]
Thanks for the report and the example code. We're still a small team right now at Pinecone and I just joined the company to work on clients/sdks. Hopefully I will get to dig into this error soon, but in the meantime you could try the experimental client we're developing in this other repository: https://github.com/pinecone-io/pinecone-client

The new client is still in an "alpha" state and could change, but building all clients off of a Rust-based core is the direction we're heading in the future.

**Comment by aandis** [comment]
hitting this too. Wanted to try out Pinecone in this AI boom and wasted a lot of time on this.

**Comment by estebanpdl** [comment]
The same problem here. Has someone found a solution to this problem? Is it something about the ids format? I can create an index, get a description, and delete an index, but cannot add vectors to the index.

**Comment by jrinder42** [comment]
Please see my comment in another issue [here](https://github.com/pinecone-io/pinecone-python-client/issues/162#issuecomment-1558023248). Basically, *requests* needs to verify SSL certificates from HTTPS requests. It seems that something is going awry in this codebase regarding this. You can use  *requests* with the verify parameter=False (**do not recommend**) or *urllib3* if you are unsure how to use the verify parameter with *requests*.

As a workaround, you can take the bits of Python you need (can pull from Pinecone examples) and create your own mini library of sorts utilizing the above solution. It is rather unfortunate, but it will solve this until an actual fix is implemented.

**Comment by ricardopinto** [comment]
I ended up using pgvector

**Comment by estebanpdl** [comment]
Qdrant is also great.

**Comment by jrinder42** [comment]
It is rather unfortunate. Qdrant and Weaviate are both great open source alternatives with a cloud offering.

**Comment by liwalayouni** [comment]
I resolved a similar issue by setting server proxy.
check solution here: https://community.pinecone.io/t/proxy-servers-with-pinecone/287/2

**Comment by anawishnoff** [comment]
As this issue is over a year old, I'll go ahead and close this as stale. However please feel free to reopen or file a new issue if you're still having issues - thank you!
