### ISSUE TITLE
[Bug] I can't create an exe using pinecone

### ISSUE THREAD

**Issue by ikrammert** [pinecone-io/pinecone-python-client#200]
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am trying to extract an exe from the code I wrote with Pinecone using pyinstaller.
`pyinstaller --onefile main.py -n pinecone.exe`

### Expected Behavior

I get this error while creating exe
```
185920 INFO: Fixing EXE headers
186784 INFO: Building EXE from EXE-00.toc completed successfully.
Generating spec file...Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "init.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "nodes\CreateIndex.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pinecone\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pinecone\core\utils\constants.py", line 33, in <module>
  File "pinecone\core\utils\__init__.py", line 53, in get_environment
  File "pathlib.py", line 1134, in read_text
  File "pathlib.py", line 1119, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\IKRAMM~1\\AppData\\Local\\Temp\\_MEI260042\\pinecone\\__environment__'
[25284] Failed to execute script 'main' due to unhandled exception!
2023/09/22 14:29:48 exit status 1

```

### Steps To Reproduce

- I just wrote the following simple code and tried to create exe with pyinstaller
1. the code 
```
import pinecone

apiKey = "my_key"
environment = "my"


pinecone.init(api_key=apiKey,environment=environment)
a= pinecone.list_indexes()
print(a)
params={}
a['name']= "helloworld"
a['dimension'] = 8
#pinecone.create_index(name="helloworld", dimension=8, metric="euclidean")
pinecone.create_index(**params)
pinecone.describe_index("helloworld")
a= pinecone.list_indexes()
print(a)
```
2.  pyinstaller --onefile a.py -n test-pinecone.exe

### Environment

```markdown
- OS: windows 11
- Python: 3.10.11
- pinecone: 2.2.4
- pyinstaller: 5.13.2
```

**Comment by anawishnoff** [comment]
Closing as this issue is stale - please reopen if you are still facing issues. Thanks!
